### PR TITLE
"Unicode Fix" for data transmission in Python 2.7

### PR DESCRIPTION
**Pull request by mazdak**
This fixes a strange unicode error that happens in Python 2.7 when trying to ddfs.chunk,

### CODE REVIEW

**Comment by jflatow** [comment]
Thanks Mazdak, this was causing problems with httplib or pycurl or both? If Python2.7 can't treat unicode strings as byte sequences anymore I guess there will be other problem spots too.

**Comment by mazdak** [comment]
It was in httplib. I haven't noticed any other issues. 

@mazdak

**Comment by JensRantil** [comment]
Just curious, will this need a test case?

**Comment by mazdak** [comment]
It's not changing any functionality, so existing test cases should cover it. 

@mazdak

**Comment by brocaar** [comment]
Thanks! I had the same error and this change fixed it for me as well.

**Comment by pmundkur** [comment]
Do you still need this patch with the latest master?

**Comment by pooya** [comment]
The underlying code has been modified.  It is not clear what problem this was supposed to resolve.

**Pull request closed without merging**
