### PR TITLE
S3 support

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by pmundkur** [comment]
Very cool work, thanks!  Would it be possible to rebase this patchset on current master and get a cleaner patch series?  This is going to be hard to pull: e.g. ef7c5a0 has new code along with upstream merge.

**Comment by srobertson** [comment]
Crazy, did not mean to submit that yet. Guess we're horrible at using git.

Feel free to delete this pull request as the s3 stuff is very alpha. We'll get you a cleaner one in the near future.

Since the cat's out of the bag, have a look at http://triv.io. We're setting up a hosted version of disco,  with a slew of goodies, most of which we'll be contributing back as soon as we're not embarrassed by them.

**Comment by pmundkur** [comment]
Great, looking forward to it!  And good luck!

**Comment by pooya** [comment]
This PR cannot be merged in its current form.

**Pull request closed without merging**
