### PR TITLE
Add a docker file (and support files) to contrib

### PR DESCRIPTION
**Pull request by gijzelaerr**
This will run a basic disco installation inside a docker container.

### CODE REVIEW

**Comment by pooya** [comment]
Would you please squash these three commits into one?
I see issue 443 when running the examples in this docker.  I will investigate further.

**Comment by gijzelaerr** [comment]
ok sure. rebase and force push or new pull request?  i'll do this tomorrow.

**Comment by pooya** [comment]
Thanks. Either one works fine.

**Comment by gijzelaerr** [comment]
did a rebase and force push.

**Pull request merged**
