### PR TITLE
update to 18.1

### PR DESCRIPTION
**Pull request by ghost**
I replaced erlang:now/0 to erlang:timestamp/0.
warn_missing_spec gets in a way of rebar eunit and triq dependency missing

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
Looks like this is failing all Travis CI tests?

Even the 18.1 test fails with:

```
disco_worker.erl:243: The call worker_throttle:handle(T::'undefined' | worker_throttle:state()) does not have an opaque term of type queue:queue(_) as 1st argument
```

**Comment by ghost** [comment]
@ErikDubbelboer opaque declaration of worker_throttle:state() confuses Dialyzer because the opaque declaration expects to find some structure declaration in its right hand side, not another opaque term

Workaround committed!

**Comment by ilovezfs** [comment]
Bump. Can this be merged? It seems to have passed your CI on the Erlang 18.1 instance. There's some discussion of "boneyarding" the Disco formula from Homebrew, since only Erlang 18.3 is currently supported in Homebrew core: https://github.com/Homebrew/legacy-homebrew/issues/46780#issuecomment-204744013

For what it's worth, I've opened a PR to Homebrew (https://github.com/Homebrew/homebrew-core/pull/181) applying the patch from this PR, but it's somewhat unlikely to be accepted unless at minimum upstream has expressed an intent to merge the patch being applied.

Also, any word on a new release tag?

**Comment by ilovezfs** [comment]
For now we've opted to go with #637  over this PR : 
https://github.com/Homebrew/homebrew-core/commit/18f6a55ae609ea4c8159e6fd093019972143d558
https://github.com/Homebrew/homebrew-core/pull/181

Please let us know when you decide how to handle Erlang >=18.1 support so we can remove the patching. Thanks.

**Comment by pooya** [comment]
Pull request #637 was merged. Thanks.

**Comment by pooya** [comment]
As of the release tag, I'll have to run the regression tests before tagging a release. It will have to happen soon because of the support for Erlang 18.

**Comment by ilovezfs** [comment]
Great, thanks.

**Pull request closed without merging**
